name: sport_infrastructure
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^6.1.3
  dio: ^3.0.10
  google_maps_flutter: ^2.0.1
  geolocator: ^7.0.1
  carousel_slider: ^3.0.0
  flutter_screenutil: ^4.0.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true